{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "818a0d92",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "from sqlalchemy import create_engine\n",
    "from sklearn.preprocessing import MinMaxScaler\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.decomposition import PCA\n",
    "from sklearn.ensemble import GradientBoostingClassifier\n",
    "from sklearn.feature_extraction.text import TfidfVectorizer\n",
    "from sklearn.metrics import classification_report, roc_auc_score\n",
    "import pickle\n",
    "import os\n",
    "import psycopg2\n",
    "from dotenv import load_dotenv\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e2116974",
   "metadata": {},
   "outputs": [],
   "source": [
    "load_dotenv()\n",
    "\n",
    "def get_connection():\n",
    "    return psycopg2.connect(\n",
    "        user=os.getenv(\"DB_USER\"), \n",
    "        password=os.getenv(\"DB_PASSWORD\"), \n",
    "        host=os.getenv(\"DB_HOST\"), \n",
    "        port=os.getenv(\"DB_PORT\"), \n",
    "        dbname=os.getenv(\"DB_NAME\") \n",
    "    )\n",
    "\n",
    "\n",
    "engine = get_connection()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "3725f444",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "              precision    recall  f1-score   support\n",
      "\n",
      "           0       0.73      0.85      0.78      1673\n",
      "           1       0.72      0.54      0.62      1185\n",
      "\n",
      "    accuracy                           0.72      2858\n",
      "   macro avg       0.72      0.70      0.70      2858\n",
      "weighted avg       0.72      0.72      0.72      2858\n",
      "\n",
      "ROC AUC: 0.7915737917432744\n",
      "Modelo para FastAPI guardado\n"
     ]
    }
   ],
   "source": [
    "\n",
    "#cargar datos \n",
    "\n",
    "QUERY = \"\"\"\n",
    "SELECT\n",
    "    m.movie_id,\n",
    "    m.budget,\n",
    "    m.revenue,\n",
    "    m.runtime,\n",
    "    m.popularity,\n",
    "    m.vote_count,\n",
    "    EXTRACT(YEAR FROM m.release_date) AS release_year,\n",
    "    m.adult,\n",
    "    m.video,\n",
    "    m.title,\n",
    "    m.overview,\n",
    "    m.tagline,\n",
    "    g.name AS genre_name\n",
    "FROM movies m\n",
    "LEFT JOIN movie_genres mg ON m.movie_id = mg.movie_id\n",
    "LEFT JOIN genres g ON mg.genre_id = g.genre_id\n",
    "WHERE m.budget > 0 AND m.revenue > 0;\n",
    "\"\"\"\n",
    "df_raw = pd.read_sql(QUERY, engine)\n",
    "\n",
    "\n",
    "#target\n",
    "df_raw['success'] = (df_raw['revenue'] > df_raw['budget'] * 2).astype(int)\n",
    "\n",
    "#features\n",
    "df_raw['adult'] = df_raw['adult'].astype(int)\n",
    "df_raw['video'] = df_raw['video'].astype(int)\n",
    "numeric_features = ['budget', 'runtime', 'popularity', 'vote_count', 'release_year', 'adult', 'video']\n",
    "\n",
    "df_movies_unique = df_raw.drop_duplicates(subset='movie_id').set_index('movie_id')\n",
    "X_num = df_movies_unique[numeric_features].fillna(df_movies_unique[numeric_features].median())\n",
    "\n",
    "#one-hot\n",
    "genre_ohe = df_raw[['movie_id', 'genre_name']].dropna()\n",
    "genre_ohe['value'] = 1\n",
    "genres_df = genre_ohe.pivot_table(\n",
    "    index='movie_id',\n",
    "    columns='genre_name',\n",
    "    values='value',\n",
    "    aggfunc='max',\n",
    "    fill_value=0\n",
    ")\n",
    "genres_df = genres_df.reindex(df_movies_unique.index, fill_value=0)\n",
    "genre_cols = genres_df.columns\n",
    "\n",
    "\n",
    "#texto\n",
    "df_movies_unique['text_combined'] = (\n",
    "    df_movies_unique['title'].fillna(\"\") + \" \" +\n",
    "    df_movies_unique['overview'].fillna(\"\") + \" \" +\n",
    "    df_movies_unique['tagline'].fillna(\"\")\n",
    ")\n",
    "\n",
    "tfidf = TfidfVectorizer(max_features=256, stop_words='english') \n",
    "X_tfidf = tfidf.fit_transform(df_movies_unique['text_combined']).toarray()\n",
    "\n",
    "pca = PCA(n_components=64, random_state=42)  \n",
    "X_text = pca.fit_transform(X_tfidf).astype('float32')\n",
    "\n",
    "\n",
    "# Dataset final\n",
    "X = np.hstack([X_num.values, genres_df.values, X_text])\n",
    "y = df_movies_unique['success'].values\n",
    "\n",
    "\n",
    "# train/test\n",
    "X_train, X_test, y_train, y_test = train_test_split(\n",
    "    X, y, test_size=0.2, stratify=y, random_state=42\n",
    ")\n",
    "\n",
    "\n",
    "# Escalado\n",
    "scaler = MinMaxScaler()\n",
    "X_train_scaled = scaler.fit_transform(X_train)\n",
    "X_test_scaled = scaler.transform(X_test)\n",
    "\n",
    "\n",
    "# Modelo\n",
    "gb = GradientBoostingClassifier(\n",
    "    n_estimators=400,\n",
    "    learning_rate=0.05,\n",
    "    max_depth=3,\n",
    "    random_state=42\n",
    ")\n",
    "gb.fit(X_train_scaled, y_train)\n",
    "\n",
    "\n",
    "#Comprobación\n",
    "y_pred = gb.predict(X_test_scaled)\n",
    "y_prob = gb.predict_proba(X_test_scaled)[:, 1]\n",
    "print(classification_report(y_test, y_pred))\n",
    "print(\"ROC AUC:\", roc_auc_score(y_test, y_prob))\n",
    "\n",
    "\n",
    "# Guardado para FastAPI\n",
    "package = {\n",
    "    'numeric_features': numeric_features,\n",
    "    'genre_columns': list(genre_cols),\n",
    "    'scaler': scaler,\n",
    "    'tfidf_vectorizer': tfidf,\n",
    "    'pca': pca,\n",
    "    'gb_model': gb\n",
    "}\n",
    "\n",
    "with open('movie_model.pkl', 'wb') as f:\n",
    "    pickle.dump(package, f)\n",
    "\n",
    "print(\"Modelo para FastAPI guardado\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "27fa3104",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "ml_stable",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.19"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
